#! /bin/bash
echo "create folder"

mkdir Files

echo "creating files"

dd if=/dev/zero of=Files/File1 bs=1M count=10
dd if=/dev/zero of=Files/File2 bs=1M count=10
dd if=/dev/zero of=Files/File3 bs=1M count=10
dd if=/dev/zero of=Files/File4 bs=1M count=10
dd if=/dev/zero of=Files/File5 bs=1M count=10

echo "DONE CREATING FILES"
